version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    container_name: papers_please
    environment:
      - POSTGRES_DB=papersplease
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5431:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local